module.exports = {
  INTERNAL_SERVER_ERROR: `Internal Server Error\n서버에서 문제가 발생했습니다.\n나중에 다시 시도해 주세요.`,
  NOT_FOUND: "페이지를 찾을 수 없습니다.",
  UNKNOWN_ERROR: "알 수 없는 오류가 발생했습니다.",
  PROBLEM: {
    NOT_FOUND: "문제를 찾을 수 없습니다.",
    TIMEOUT: `코드 실행 시간이 너무 길어요.\n무한 루프를 발생시키는 코드가 있는지 확인해주세요.`,
    NO_SOLUTION_FUNC: "'solution' 함수가 정의되지 않았습니다.",
    FAILURE: "테스트를 통과하지 못했습니다ㅠㅠ",
    SUCCESS: "축하합니다!! 정답입니다 :)",
  },
  AUTH: {
    NEED_ID_PW: "아이디 또는 비밀번호를 입력해주세요.",
    LOGIN_PROCESS: "로그인 요청 처리 중 문제가 발생했습니다.",
    LOGOUT: "로그아웃 중에 오류가 발생했습니다.",
    SIGNUP_PROCESS: "회원가입 처리 중 문제가 발생했습니다.\n나중에 다시 시도해주세요.",
    EXISTING_ID: "이미 존재하는 ID입니다.",
    NOT_AUTHENTICATED: "로그인한 상태가 아닙니다.",
  },
}
